image: Visual Studio 2022

skip_branch_with_pr: true
skip_tags: true
skip_commits:
  files:
    - "**/*.md"

environment:
  Appveyor: true

init:
  - git config --global core.autocrlf input

nuget:
  disable_publish_on_pr: true

build_script:
  # Our stuff
  - ps: .\build.ps1 -PullRequestNumber "$env:APPVEYOR_PULL_REQUEST_NUMBER" -CreatePackages $true

test: off
artifacts:
  - path: .\.nupkgs\*.nupkg

deploy:
  - provider: NuGet
    server:
    on:
      branch: main
    api_key:
      secure: Tsm27Yg1J/9f/zj96jqNAyxK+bwpp1Ew61C1wA7k89D6MHUFvKPGvon2LsHGjddg
    skip_symbols: false
    symbol_server: https://www.myget.org/F/stackoverflow/symbols/api/v2/package
    artifact: /.*(\.|\.s)nupkg/
