name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build .NET project
        run: dotnet build Build.csproj -c Release /p:CI=true
      - name: Test
        run: dotnet test Butters.Extensions.String.sln --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage /p:CI=true /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
      - name: Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          # directory: ./coverage/**/
          fail_ci_if_error: true
      - name: Pack nugets
        run: dotnet pack ".\Build.csproj" --no-build -c Release /p:PackageOutputPath=$packageOutputFolder /p:CI=true
      - name: Push to NuGet
        run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json
