name: Main Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build .NET project
        run: dotnet build Build.csproj -c Release /p:CI=true
      - name: Test
        run: dotnet test tests/Butters.Extensions.String.Tests/Butters.Extensions.String.Tests.csproj -c Release --logger trx --results-directory TestResults /p:CI=true
